### ISSUE TITLE
Celo Governance Call 17 | June 7th, 2022

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#134]
# Celo Governance Call 17

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: June 7th, 2022. 12 PM ET / 9 AM PT 60 minutes max
Where: https://meet.google.com/ean-avno-img

## Agenda
* [CGP52](https://github.com/celo-org/governance/blob/main/CGPs/cgp-0052.md) (Climate Collective Treasury)
* Proof-of-Deposit CGP (Upcoming, to be added) (Resources: [Forum post](https://forum.celo.org/t/proof-of-deposit-summary-and-faqs/3699), [Summary & FAQs](http://files.cambridgecryptographic.com/whitepapers/PoD_Summary_and_FAQs_31.5.22.pdf), [Slide deck](http://files.cambridgecryptographic.com/outreach/PoD_slidedeck_30.5.22.pdf))
* [CGP 53](https://github.com/celo-org/governance/blob/main/CGPs/cgp-0053.md)
* CGP 54 [Re-opening community fund, to be added]

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by willkraft** [comment]
@anranga95 Great! I'll add to the agenda

**Comment by yc5915** [comment]
We would like to discuss our upcoming Proof-of-Deposit CGP on this governance call (will edit in the link to our new thread with latest docs soon)

**Comment by willkraft** [comment]
@gastonponti great, I'll add it to the agenda

**Comment by m-chrzan** [comment]
Hey @willkraft, I know we missed the boat with Call 17, but would love another governance call soon where we could talk about [CGP 55](https://github.com/celo-org/governance/blob/f7a9f331d50d8793d1305cd9880723f96e396bdb/CGPs/cgp-0055.md) (Core Contracts Release 7). Ideally next week, as the mainnet proposal date is slated for June 21. Here's the forum post: https://forum.celo.org/t/core-contracts-release-7/3778.

**Comment by willkraft** [comment]
Hey Martin, what's your discord handle? It's good to hear from you by the way!

**Comment by willkraft** [comment]
Hi all, see [here](https://docs.google.com/document/d/14ZDoExC5ljAOwOiM2wVXmtizNW5I9dEOhPqb0MPY3n4/edit#) for the notes from the call.
