### ISSUE TITLE
Celo Governance Call 18 | June 16th, 2022

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/governance#142]
# Celo Governance Call 18

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: June 16th, 2022. 12 PM ET / 9 AM PT 60 minutes max
Where: https://meet.google.com/mbj-brpc-dux

This Governance Call to be led by @martinvol.

## Agenda (in order)
* [Adding community-run oracles - CGP 57](https://github.com/celo-org/governance/pull/143/files)
* [CR7 - CGP 55](https://github.com/celo-org/governance/blob/main/CGPs/cgp-0055.md)
* [One-to-one stable value asset basket and 50/50 DAI-USDC-Split - CGP 56](https://github.com/celo-org/governance/blob/roman/cgp-0056/CGPs/cgp-0056.md)

[Add to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NXFnNmppc2xocnA4YmZ2ZjBnaXNsNjZlOHIgbWFydGluLnZvbHBlQGNsYWJzLmNv&tmsrc=martin.volpe%40clabs.co)

**Comment by diwu1989** [comment]
I'll be able to attend for only the first 30 mins of the call.
As for the community oracle reporter initiative, I'll be deploying the oracle reporter into GCP US Central region where I already have excess capacity.

**Comment by martinvol** [comment]
Here's the recording: https://drive.google.com/file/d/1PLyxSxPdsfOeMTTAE9JUfumg0Vtcz9Mp/view?usp=drivesdk
