### ISSUE TITLE
Celo Governance Call #22 | October 13th, 2022

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#169]
# Celo Governance Call #22

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: October 13th, 2022 (Thurs). 12 PM ET / 9 AM PT 60 minutes max
Where: meet.google.com/vye-odmb-eim

## Agenda
* [Africa DAO Proposal](https://forum.celo.org/t/celo-africa-regional-dao-proposal/4054)
* [LatAm DAO Proposal](https://forum.celo.org/t/latam-w3-dao-proposal/4494)
* [Changes to Kuneco calls](https://forum.celo.org/t/kuneco-2-0-evolution-of-kuneco-into-a-community-townhall/4268)
* Meta governance discussions

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by willkraft** [comment]
Hi all, we do not have any proposals to discuss, so we are pushing this call to 10/13.

**Comment by herlew** [comment]
Discussion around Celo Africa Regional DAO [Proposal ](https://forum.celo.org/t/celo-africa-regional-dao-proposal/4054)

**Comment by ericnakagawa** [comment]
@willkraft can aliu have time to review the Africa dao?

**Comment by willkraft** [comment]
Definitely, thanks for the tag!

**Comment by MilaRioja** [comment]
Wanted to add [LatAm DAO proposal ](https://forum.celo.org/t/latam-w3-dao-proposal/4494)for discussion!

**Comment by willkraft** [comment]
Hi all, please see the recording [here](https://drive.google.com/file/d/1iMwYwVAHljSqEWQxUwtuF4RWhpPaQzEt/view) and the notes [here](https://docs.google.com/document/d/14r_wtxcD5sGQe1UvQpKPJfkuDIYaejQ91s1tJsRDHes/edit#)
