### ISSUE TITLE
Celo Governance Call #23 | November 17th, 2022

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#178]
# Celo Governance Call #23

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: November 17th, 2022 (Thurs). 12 PM ET / 9 AM PT 60 minutes max
Where: meet.google.com/kfh-krsc-bbi

## Agenda
1.  [Celo India DAO #1 Proposal - (Chitty)](https://forum.celo.org/t/celo-indiadao-reginal-dao-proposal/4207/25)
2. [Celo India DAO #2 Proposal - (Monish)](https://forum.celo.org/t/proposal-celo-india-dao/4544?u=monish016)
3. [CGP 63: Learn to Earn](https://forum.celo.org/t/proposal-cgp-63-learn-to-earn-campaign-with-creal-and-celo-in-brazil/4772)
4. Celo Community Fund Update

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by cryptochitty** [comment]
https://forum.celo.org/t/celo-indiadao-regional-dao-proposal/4207

**Comment by lopeselio** [comment]
> # Celo Governance Call #23
> ![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)
> 
> When: November 17th, 2022 (Thurs). 12 PM ET / 9 AM PT 60 minutes max Where: meet.google.com/kfh-krsc-bbi
> 
> ## Agenda
> 1. [Celo India DAO #1 Proposal - (Chitty)](https://forum.celo.org/t/celo-indiadao-reginal-dao-proposal/4207/25)
> 2. [Celo India DAO #2 Proposal - (Monish)](https://forum.celo.org/t/proposal-celo-india-dao/4544?u=monish016)
> 3. [LatAm DAO Proposal](https://forum.celo.org/t/latam-w3-dao-proposal/4494)
> 4. Climate Collective Proposal
> 5. Celo Community Fund Update
> 
> _Please post all relevant proposals below that should be discussed and evaluated_

https://github.com/celo-org/governance/pull/180

**Comment by deboraconconi** [comment]
[]([CGP 63: Learn to Earn Campaign with cReal and Celo in Brazil](https://forum.celo.org/t/proposal-cgp-63-learn-to-earn-campaign-with-creal-and-celo-in-brazil/4772))

**Comment by willkraft** [comment]
Hi all, please see the notes [here](https://docs.google.com/document/d/1Rc9teiHucdljaZvnaFtZj44H2szFH5CXC2-Af1vYDUI/edit) and the recording [here](https://drive.google.com/file/d/1M6UMR_ti0zaO98i7Db1j15yi0b3zcjDO/view) -- sharing permissions on the recording will be updated soon
