### ISSUE TITLE
Celo Governance Call #24 | December 8th, 2022

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#182]
# Celo Governance Call #24

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: December 8th, 2022 (Thurs). 12 PM ET / 9 AM PT 60 minutes max
Where: meet.google.com/qmi-qfej-bpn

## Agenda
* [Celo Africa DAO](https://forum.celo.org/t/celo-africa-regional-dao-proposal/4054)
* [Celo Tribe Web3 University Social Clubs](https://forum.celo.org/t/proposal-celo-tribe-web3-social-club-for-universities/4861)
* [Celo LatAm DAO](https://forum.celo.org/t/latam-w3-dao-proposal/4494)

_Please add a comment below to add a proposal to the agenda_

**Comment by ericnakagawa** [comment]
* Matthieu Chamson would like to discuss Gas a new proposal. We can expect a draft proposal in next two weeks, prior to the discussion.

**Comment by ericnakagawa** [comment]
* Aliu, Africa eco lead, would also like to bring an updated Africa dao prooosal to the community discussion here.
* Mila, LatAm ecolead, may also wish to share their update proposal.

**Comment by Hawwal** [comment]
Hello, I would love to be part of this call, I want to share an Idea regarding "Celo Tribe" which is a web3 social club for universities. Thanks.

**Comment by willkraft** [comment]
Thanks @ericnakagawa and @Hawwal, I'll add these to the agenda. I'll check with Mila in the forum if she'd like to discuss the LatAm proposal

**Comment by ericnakagawa** [comment]
Please add Gas price increase as agenda topic (https://github.com/celo-org/governance/pull/176) -- CGP # to be assigned.

**Comment by willkraft** [comment]
Hi all, please see the notes [here](https://docs.google.com/document/d/1Xt79M1UauI8RtVSZjn9UNAdsSclA9bzykObp3csKty0/edit#) and the recording [here](https://drive.google.com/file/d/1eFA5c_xV2gcgAsL0mAiPwe2PeGl2V0dv/view)
