### ISSUE TITLE
Celo Governance Call #25 | January 26th, 2023

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#193]
# Celo Governance Call #25

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: January 26th, 2022 (Thurs). 12 PM ET / 9 AM PT 60 minutes max
Where: meet.google.com/ipj-uqar-jmt

## Agenda
• [Bug Bounty Program for Celo on Immunefi](https://github.com/celo-org/governance/issues/205)
• [Increase Minimum Gas Threshold](https://celo.stake.id/#/proposal/83)
• Improvements to Approval process

_Please add a comment below to add a proposal to the agenda_

**Comment by willkraft** [comment]
Hi all, there are no proposals to discuss yet, so we are moving this call to 1/26. Let me know if you’d like to discuss anything!

**Comment by vissequ** [comment]
What about my proposal?

**Comment by vissequ** [comment]
https://github.com/celo-org/governance/issues/205

**Comment by willkraft** [comment]
Hi @vissequ, thanks for asking, I've added your proposal to the agenda for 1/26.

**Comment by vissequ** [comment]
Thank you sir!

**Comment by ericnakagawa** [comment]
Can we include a segment on https://celo.stake.id/#/proposal/83 ?

**Comment by willkraft** [comment]
@ericnakagawa yeah, just added to the agenda

**Comment by willkraft** [comment]
Hi all, please find the notes from the call [here](https://docs.google.com/document/d/1fRyftPv7if6yrR3FRMPvuPQF8E96G5058D59lKChHKA/edit#) and the recording [here](https://drive.google.com/file/d/1W9JWb5PEcAcrpMlB0LhkBxtHa3Cj_UHL/view)
