### ISSUE TITLE
Proposal: Establish and Fund a Bug-Bounty Program for Celo on Immunefi

### ISSUE THREAD

**Issue by vissequ** [celo-org/governance#205]
**Proposal:** Establish and Fund a Bug-Bounty Program for Celo on Immunefi.

**Summary:** Create a bug-bounty program on Immunefi and allocate 1,000,000 CELO from community governance funds.

**Purpose:** To incentivize community members and professional white hat hackers to uncover and fix any bugs that may exist within the Celo Protocol.

For comparison, here is a list of other major blockchains and web3 services currently using Immunefi:

- Wormhole ($10,000,000* US in rewards)
- MakerDAO ($10,000,000* US in rewards)
- Polygon ($2,100,000* US in rewards)
- Optimism ($2,000,000* US in rewards)
- Algorand ($2,000,000* US in rewards)
- Gnosis ($2,000,000* US in rewards)
- Arbitrum ($2,000,000* US in rewards)

_*Data from January 9, 2023_

---------------------------------------------------------

**Proposed Multi-Signatories:**

_**5 out of 7 of the multi-signatories must approve transactions and they are collectively responsible for verifying that a solution to a particular bug is functioning properly before the bounty hunter is compensated:**_

_**Indicates that the individual is a person of interest and has not yet committed OR that it is an open slot:_

- **Ryon** – Celo Foundation, Security
- **Dave** – Celo Foundation, Security
- **Ben** - cLabs, Security
- **Connor** (vissequ)- Community Moderator
- **_A Member of the Valora Team_
- **_(Bogdan) - Mento_
- **_(DiWu) - Community Member & Validator_

Hardware wallets will be required for each individual signatory.

---------------------------------------------------------

**Additional Resources:**

- [Bug Bounty White Paper](https://docs.google.com/document/d/1sTFNu5zPngsygW0Q2HOhEWGuElsSIsJVyQQm-6mXeYY/edit)
- [Immunefi](https://immunefi.com/)

**Point of Contact**:

_Please feel free to reach out on Discord with any questions:_
**vissequ | Celo#9060**

**Comment by willkraft** [comment]
Hi @vissequ, thanks for preparing this! Would you mind submitting a pull request and creating a CGP using the template below?

https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md

**Comment by vissequ** [comment]
> Hi @vissequ, thanks for preparing this! Would you mind submitting a pull request and creating a CGP using the template below?
> 
> https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md

Hey Will my sincere apologies for the delay. We are still working on finalizing certain aspects, but I would love still love to give a presentation tomorrow if that is possible.

**Comment by willkraft** [comment]
@vissequ no worries, that sounds good - see you tomorrow!
