### ISSUE TITLE
Celo Governance Call #26 | February 28th, 2023

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#212]
# Celo Governance Call #26

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: Tuesday, February 28th, 2023. 11 AM ET / 8 AM PT 60 minutes max
Where: meet.google.com/gxd-mznf-izg

## Agenda
• [Mento Upgrade 01 (MU01)](https://forum.celo.org/t/proposal-mu01-phase1-multicollateral-mento/5245)
• [Mento Reserve: Return CELO](https://forum.celo.org/t/mento-reserve-returning-celo/5236)
• Prezenti proposal draft

_Please add a comment below to add a proposal to the agenda_

**Comment by bowd** [comment]
Mento-Upgrade-01 (MU01) CGP is scheduled for early March! 
I want to take this time to chat about what's happening and the structure of the CGP.

**Comment by willkraft** [comment]
@bowd sounds great, I'll add it to the agenda

**Comment by willkraft** [comment]
Hi @bowd, do you have a CGP or forum post on this proposal?

**Comment by bowd** [comment]
> Hi @bowd, do you have a CGP or forum post on this proposal?

Not yet, but will have something by then.

**Comment by CeloDaily** [comment]
Hi,  

Can I present this proposal in the call? 

https://forum.celo.org/t/proposal-funding-for-celodaily-to-boost-ecosystem-growth/5221

**Comment by willkraft** [comment]
@bowd sounds good!

@CeloDaily definitely, I'll add you to the agenda

**Comment by CeloDaily** [comment]
Sorry but can I do this at the next time? I need a time for preparing a deck, since I found a negative feedback about the proposal.

**Comment by juanjgiraldoc** [comment]
@CeloDaily sure np 👍

**Comment by willkraft** [comment]
Done!

**Comment by juanjgiraldoc** [comment]
Recording: https://drive.google.com/file/d/1V__TEmGJt-Y_lu8m5yDs2Sq0SQoSY73z/view

**Comment by willkraft** [comment]
Hi all, please see here for notes from the call: https://docs.google.com/document/d/1H6LMvgPafkwpcQHyiLVLH98hpCGqnz6lExUMDXxMh9Q/edit#heading=h.1ele2p5gjpk0
