### ISSUE TITLE
Celo Governance Call #27 | March 28th, 2023

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#220]
# Celo Governance Call #27

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: Tuesday, March 24th, 2023. 12:30 PM ET / 9:30 AM PT 60 minutes max
Where: meet.google.com/qdg-mpwi-ijq

## Agenda
• [Join Chainlink Scale Program](https://forum.celo.org/t/celo-to-join-chainlink-scale-program-to-accelerate-ecosystem-growth/5360)

_Please add a comment below to add a proposal to the agenda_

**Comment by ericnakagawa** [comment]
Let's save time for an upcoming Chainlink CGP proposal. CGP # to TBD.

**Comment by willkraft** [comment]
Hi all, the main proposal to discuss would like to move the call up to Friday, so we have moved the called to 3/24 at 9:30am PT.

**Comment by willkraft** [comment]
Hi all, see notes from the call [here](https://docs.google.com/document/d/1zzOoZkrOGB0lgxwdnwjvPbOaihqzfivM9Md8O4Y5QVA/edit#) and the recording [here](https://drive.google.com/file/d/1w3veCtuZTZjU43Z0vmjjVd39A7G3jvA4/view).
