### ISSUE TITLE
Celo Governance Call #28 | April 14th, 2023

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#231]
# Celo Governance Call #28

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: Tuesday, April 14th, 2023. 11am ET / 8am PT 60 minutes max
Where: [meet.google.com/arw-cetd-rwt](https://meet.google.com/arw-cetd-rwt)

## Agenda

* [On-Chain Offset Proposal](https://forum.celo.org/t/on-chain-offsets/5471)

**Comment by Juancamp1987** [comment]
Will be interesting to talk about approvers and how to avoid proposals get rejected when they passes the "Upvote" step and get dequeued.

**Comment by ericnakagawa** [comment]
Currently exploring shifting this call up a week.

**Comment by ericnakagawa** [comment]
Suggesting inviting the authors of https://forum.celo.org/t/on-chain-offsets/5471 to speak on their upcoming CGP.

**Comment by willkraft** [comment]
Hey all, the notes can be found [here](https://docs.google.com/document/d/1hNQXqpJStqz14hUv20rmCkIcPPS0w3CdWoYL3l_Cu_w/edit) and the recording can be found [here](https://drive.google.com/file/d/1fk6Jtinn1j8NQzmZjXeOazJqrn2CF2m6/view).
