### ISSUE TITLE
Celo Governance Call #30 | May 30th, 2023

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#268]
# Celo Governance Call #30

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

When: Tuesday, May 30th, 2023. 11am ET / 8am PT 60 minutes max
Where: meet.google.com/uor-coam-nsw

## Agenda

* [Emerging Artist Growth Fund](https://forum.celo.org/t/emerging-artist-and-impact-growth-fund/5804)
* [Celo Europe DAO](https://forum.celo.org/t/celo-europe-dao/5443/16)
* Common Stacks

**Comment by willkraft** [comment]
Hey all, we don't have any topics to discuss yet, so we are postponing to 5/30.

**Comment by AriSwap** [comment]
I'd like to propose discussing the Emerging Artist and NFT for impact fund proposed by us in the Forum

**Comment by AriSwap** [comment]
We can have some artist join the call as well as myself and our marketing team

**Comment by AriSwap** [comment]
@willkraft see the proposed topic.

**Comment by 0xzoz** [comment]
> @willkraft see the proposed topic.

@AriSwap thanks for this. I have added the topic with a link to the forum post. In the meantime would you like to draft a proposal and add as a PR? I couldnt see a draft in the repo or incoming PR's.

**Comment by AriSwap** [comment]
Yes. Can you please share the link to add

**Comment by AriSwap** [comment]
@Juancamp1987 can you send the link for us to add the proposal

**Comment by juanjgiraldoc** [comment]
Yo can find here [Notes](https://docs.google.com/document/d/1AOhgqO2i45Do4bSqcKPKeQZIChbkimgWzi1UdRlzSsc/edit) and [Recording](https://drive.google.com/file/d/135xyVhpsrotdgMFhRFuG8Y_0ASLh9iHv/view?usp=drive_link)
