### ISSUE TITLE
Celo Governance Call #31 | June 14th, 2023

### ISSUE THREAD

**Issue by willkraft** [celo-org/governance#269]
Celo Governance Call https://github.com/celo-org/governance/issues/31

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

When: Wednesday, June 14th, 2023. 11am ET / 8am PT 60 minutes max
Where: meet.google.com/miw-mpai-fpk

## Agenda
* Contract Release 10: https://github.com/celo-org/celo-monorepo/issues/10375

**Comment by willkraft** [comment]
Hi all, we moved this call to Wednesday, June 14th at 11am ET / 8am PT because the original time conflicts with another large event in the Celo community.

**Comment by juanjgiraldoc** [comment]
**Resources:**
-Notes
-[Recording](https://drive.google.com/file/d/1kl4uLeLsDDejfntYnE0yp9gNER5uvtZ-/view)
