### ISSUE TITLE
Celo Governance Call #34 | August 8th, 2023

### ISSUE THREAD

**Issue by 0xzoz** [celo-org/governance#286]
# Celo Governance Call #34

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**- When:** Tuesday, August 8th, 2023. 8:00 am PT / 11:00 am ET / 3:00 pm UTC 60 minutes max
**- Lu.ma event:** https://lu.ma/CGP34
**- Where:** [meet.google.com/iyt-sktc-keq](https://meet.google.com/iyt-sktc-keq)

## Agenda
- [Web3 x SDG Climate Events](https://forum.celo.org/t/proposal-web3-x-sdg-event-proposal-for-road-to-cop28/6225)
- Mobile First Community
- [ReFi DAO x Celo](https://forum.celo.org/t/proposal-refi-dao-x-celo-onboarding-the-next-generation-of-talent-and-capital/6243)

**Comment by ricaax** [comment]
Hello I'd love to add to the agenda the discussion on the proposal [[Proposal] ReFi DAO x Celo - Onboarding the next generation of talent and capital](https://forum.celo.org/t/proposal-refi-dao-x-celo-onboarding-the-next-generation-of-talent-and-capital/6243). Thank you Rica

**Comment by willkraft** [comment]
@ricaax just added you to the agenda!

**Comment by JeanneBloch** [comment]
this is great, thank you!
