### ISSUE TITLE
Celo Governance Call #35 | August 25th, 2023

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#305]
# Celo Governance Call #35

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**- When:** Friday, August 25th, 2023. 8:30 am PT / 11:30 am ET / 3:30 pm UTC 60 minutes max
**- Lu.ma event:** https://lu.ma/CGP-0035
**- Where:** meet.google.com/iyt-sktc-keq
**- Video:** [here](https://drive.google.com/file/d/1z71cuszC0WkBVCJto5glIsQuYUl2EymT/view)
**- Notes:**

## Agenda
```[tasklist]
### CGP-0095: Centrifuge Deployment on Celo
- [ ] https://github.com/celo-org/governance/blob/main/CGPs/cgp-0095.md
- [ ] https://forum.celo.org/t/centrifuge-deployment-on-celo/6405
```

**Comment by sholasparks** [comment]
hello, i'd like to chip in on this call to discuss a recent proposal update?

**Comment by anranga95** [comment]
Requesting that CGP-95 be included on the agenda. Representatives from Centrifuge will present the proposal.
[Forum Post](https://forum.celo.org/t/centrifuge-deployment-on-celo/6405)
[Github PR](https://github.com/celo-org/governance/pull/322)
