### ISSUE TITLE
Celo Governance Call #36 | September 29th, 2023

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#324]
# Celo Governance Call #36

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**- When:** Friday, September 29th, 2023. 8:30 am PT / 11:30 am ET / 3:30 pm UTC 60 minutes max
**- Lu.ma event:** https://lu.ma/CGP-0036
**- Where:** [http://meet.google.com/iyt-sktc-keq](https://www.google.com/url?q=http://meet.google.com/iyt-sktc-keq&sa=D&source=calendar&ust=1693755193607078&usg=AOvVaw3leGyEmZIe5wjRkXPBqJtH)
**- Notes:** [Here](https://docs.google.com/document/d/1_rUQmnjIv33aIcpGbI9EZ-7BiuxVFRXBUidg3j6UJFY/edit?usp=sharing) 
**- Video:** [Here](https://drive.google.com/file/d/1wP1nUl7_m0dW5Kslp3GTVpleUhFCdk3S/view)

## Agenda

```[tasklist]
### CGP-101: Temp check for gov approval multisig changes
- [ ] https://github.com/celo-org/governance/pull/342
- [ ] https://forum.celo.org/t/we-need-to-talk-about-governance/6409/26
```
```[tasklist]
### CGP-TBD: Funding for cLabs blockchain public goods work
- [ ] https://forum.celo.org/t/funding-for-clabs-blockchain-public-goods-work/6569/13
- [ ] CGP-TBD
```

```[tasklist]
### CGP-104:  cLabs: Discuss Gas Increase
- [ ] https://forum.celo.org/t/proposal-to-increase-block-gas-limit-to-50m-gas-coming-soon/6633
- [ ] https://github.com/celo-org/governance/pull/345
```

```[tasklist]
### CGP-TBD: Redstone Oracles data provider for Mento
- [ ] https://github.com/celo-org/governance/pull/343
- [ ] https://forum.celo.org/t/cgp-102-add-redstone-as-an-oracle-provider-for-mento/6627
```

```[tasklist]
### CGP-0103: Dunia launching on Celo
- [ ] https://github.com/celo-org/governance/pull/344
- [ ] https://forum.celo.org/t/dunia-launching-exof-on-celo/6261/1
```

**Comment by jakub-wojciechowski** [comment]
Hi guys, this is Jakub - founder of Redstone Oracles. We'd love to join the call to present our proposal of becoming an additional data provider for the Mento protocol.

**Comment by juanjgiraldoc** [comment]
Hello @jakub-wojciechowski before you are able to present the proposal in Governance Call you need to do a Forum Post and let people engage in the conversation around. 
Did you already did that? If not you can make one [here](https://forum.celo.org/)

**Comment by thelazyceo1** [comment]
@juanjgiraldoc could you add the eXOF proposal also to the agenda doc
