### ISSUE TITLE
README should be updated with new on-chain governance flow

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/governance#341]
As of [Contracts Release 9](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v9), the Approval and Referendum stages of on-chain governance run in parallel. The README in this repo [still refers to the old flow](https://github.com/celo-org/governance#governance-process--steps-for-proposal-creators), where Approval lasts only 1 day, before Referendum starts.

**Comment by 0xzoz** [comment]
Preemptively awaiting proposal from the discussion and work being completed in this [outline](https://forum.celo.org/t/celo-governance-development-sprint-ahead-of-cel2/6742) to avoid duplicative work
