### ISSUE TITLE
Celo Governance Call #37 | October 27th, 2023

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#346]
# Celo Governance Call #37

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**- When:** Friday, October 27th, 2023. 8:30 am PT / 11:30 am ET / 3:30 pm UTC 60 minutes max
**- Lu.ma event:** https://lu.ma/CGC-0037
**- Where:** [http://meet.google.com/iyt-sktc-keq](https://www.google.com/url?q=http://meet.google.com/iyt-sktc-keq&sa=D&source=calendar&ust=1693755193607078&usg=AOvVaw3leGyEmZIe5wjRkXPBqJtH)
**- Notes:** [TBD]() 
**- Video:** [TBD]()

## Agenda
```[tasklist]
### CGP-TBD: Celo Dapps over Apps
- [ ] https://forum.celo.org/t/proposal-celo-dapps-over-apps/6743
- [ ] CGP-TBD
```
```[tasklist]
### CGP-TBD: Mento Core Contract Upgrade #1 - Multi Collateral Mint
- [ ] https://forum.celo.org/t/mento-core-contract-upgrade-1-multi-collateral-mint/4942
- [ ] CGP-TBD
```
```[tasklist]
### CGP-TBD: $cCOP - Initial Liquidity and Marketing Plan
- [ ] https://forum.celo.org/t/ccop-initial-liquidity-and-marketing-plan/6761
- [ ] CGP-TBD
```

```

**Comment by andresl** [comment]
Hey we also want to add the [$cCOP - Initial Liquidity and Marketing Plan](https://forum.celo.org/t/ccop-initial-liquidity-and-marketing-plan/6761) to the next governance call October 27.

Thanks !

**Comment by philbow61** [comment]
Hey @juanjgiraldoc, 
the Mento team is preparing the final steps for the Mento v2 upgrade. https://forum.celo.org/t/mento-core-contract-upgrade-1-multi-collateral-mint/4942
We would like to talk about some changes that might affect other Celo ecosystem members. Could we add Mento v2 to the next governance call on the 27th of October 2023?

Thank you.
