### ISSUE TITLE
Celo Governance Call #39 | January 19th, 2024

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#369]
# Celo Governance Call #39

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

- When: Friday, January 19th, 2024. 8:30 am PT / 12:30 am ET / 4:30 pm UTC 60 minutes max
- Where: [https://lu.ma/CGC-0039](https://lu.ma/CGC-0039)
- Notes: [TBD](https://github.com/celo-org/governance/issues/369)
- Video: [TBD](https://github.com/celo-org/governance/issues/369)

## Agenda

```[tasklist]
### Celo Tribe Follow-Up Proposal
- [ ] https://github.com/celo-org/governance/pull/368
- [ ] https://forum.celo.org/t/proposal-celo-tribe-web3-social-club-for-universities/4861/22
```
```[tasklist]
### Celo Camp 2024 H1 Proposal
- [ ] TBA
- [ ] https://forum.celo.org/t/celo-camp-2024-grant-the-minipay-launchpad-and-startup-pathway-program/7206
```
```[tasklist]
### Celo Governance Guidelines and Public Goods Funding Strategy H1 2024
- [ ] TBA
- [ ] https://forum.celo.org/t/draft-celo-governance-guidelines-and-public-goods-funding-strategy-h1-2024/7200
```
```[tasklist]
### Celo Ecosystem Liquidity Operation Guild (CELO-Guild)
- [ ] TBA
- [ ] [TBA](https://forum.celo.org/t/celo-ecosystem-liquidity-operation-guild-celo-guild-allocate-portion-of-celo-in-the-celo-community-fund-to-solve-liquidity-challenges-faced-by-celo-projects-and-accelerate-the-growth-of-the-celo-ecosystem-celo-governance-proposal-draft/7243)
```

**Comment by Hawwal** [comment]
Hello @juanjgiraldoc please add the [Celo Tribe Follow-up proposal](https://forum.celo.org/t/proposal-celo-tribe-web3-social-club-for-universities/4861/22?u=hawwal) to the call agenda. Thanks

**Comment by ericnakagawa** [comment]
Celo Camp and two other proposals coming by next week and requesting to join agenda.
