### ISSUE TITLE
Celo Governance Call #40 | January 24th, 2024

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#377]
# Celo Governance Call #40 | January 24th, 2024

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

- When: Friday, January 24th, 2024. 8:30 am PT / 11:30 am ET / 4:30 pm UTC 45 minutes max
- Where: [https://lu.ma/CGC-0040](https://lu.ma/CGC-0040)
- Notes: [TBD](https://github.com/celo-org/governance/issues/377)
- Video: [Here](https://drive.google.com/drive/folders/1qQgL5kZCl3hvQQRoM7QRySy2thDBqjPe)

## Agenda

```[tasklist]
### Celo Governance Guidelines and Public Goods Funding Strategy H1 2024
- [ ] https://github.com/celo-org/governance/pull/378
- [ ] https://forum.celo.org/t/draft-celo-governance-guidelines-and-public-goods-funding-strategy-h1-2024/7200
```

**Comment by xolutionist** [comment]
hi @juanjgiraldoc would like to present https://forum.celo.org/t/invitation-to-invest-in-bringing-climate-solutions-to-sub-saharan-africa/7224/4?u=xolutionist during the Community call.

**Comment by mitchelle360** [comment]
helo, would like to join the call to discuss a proposal https://forum.celo.org/t/draft-celo-pacific-initiative/7273/6?u=mitchelle i asked last call but call was full. @juanjgiraldoc

**Comment by juanjgiraldoc** [comment]
Sorry for last minute announcement of the call. I know it was a little bit rushed.
The necessity of this call was due to the impossibility of [@LuukDAO](https://forum.celo.org/u/luukdao) to present the proposal last call and due to a lot of interactions and questions expected in his proposal this governance Call are gonna be held only to present this proposal.

For this reason @xolutionist @mitchelle360 is not posible you can present proposals in this call, but you will have the possibility to schedule your proposals for the next Regular Governance Call.
