### ISSUE TITLE
Celo Governance Call #42 | February 15th, 2024

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#392]
# Celo Governance Call #42 | February 15th, 2024

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**Before Call Info:**
- When: Thursday, February 15th, 2024. 9:30 am PT / 12:30 m ET / 5:30 pm UTC / 6:30 pm CET 45 minutes max
- Where: [https://lu.ma/CGC-0042](https://lu.ma/CGC-0042)

**After Call Info:**
- Notes: Missing
- Video: [Here](https://drive.google.com/file/d/1-W0-pvlCevw7wPDWx59oWsVOcP1IKFHW)

## Agenda
```[tasklist]
### Celo Governance Guidelines and Public Goods Funding Strategy H1 2024
- [ ] https://github.com/celo-org/governance/blob/main/CGPs/cgp-0115.md
- [ ] https://forum.celo.org/t/draft-celo-governance-guidelines-and-public-goods-funding-strategy-h1-2024
```

**Comment by juanjgiraldoc** [comment]
Special Note for this Call. Agenda is Closed. Call Scheduled only to allow discussions about [Celo Governance Guidelines and Public Goods Funding Strategy H1 2024](https://forum.celo.org/t/draft-celo-governance-guidelines-and-public-goods-funding-strategy-h1-2024)

**Comment by PushHandle** [comment]
^ **Thursday**, February 15th
