### ISSUE TITLE
Celo Governance Call #45 | April 11th, 2024

### ISSUE THREAD

**Issue by juanjgiraldoc** [celo-org/governance#420]
# Celo Governance Call #45 | April 11th, 2024

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**Before Call Info:**
- When: Thursday, April 11th, 2024, 7:00 PT / 10:00 ET / 14:00 UTC / 16:00 CET 60 minutes max
- Where: [https://lu.ma/CGC-0045](https://lu.ma/CGC-0045)

**After Call Info:**
- Notes: [Here](https://docs.google.com/document/d/1CnUnIm8bSIbU332Paerjl_l83o0dlnHfZFTM655Z50U)
- Video: [Here](https://drive.google.com/file/d/1SDLz0RpqJfaderZUBohEcL-GAZvo3ZtR)

**Proposals for Discussion**
Crowdsourced on the forum and Github prior to the meeting.
:bangbang: *(Max Proposals per Call: 3 Proposals)*

## Agenda
```[tasklist]
### Topic 1:  25 min Present / 10 Min Q&A - Mento Spin-off and Launch of the MENTO token
- [ ] [Forum Post](https://forum.celo.org/t/mento-spin-off-and-launch-of-the-mento-token)
- [ ] [Github PR]()
```
```[tasklist]
### Topic 2: 10 min Present / 5 min Q&A - Grant request to deploy Tokpay a Tokenized US T-bill infrastructure for African retail investors on Celo Mainnet
- [ ] [Forum Post](https://forum.celo.org/t/draft-grant-request-to-deploy-tokpay-a-tokenized-us-t-bill-infrastructure-for-african-retail-investors-on-celo-mainnet)
- [ ] [Github PR]()
```
```[tasklist]
### Topic 3: Proposal for Funding Stabila: Driving Stablecoin Adoption on Celo
- [ ] [Forum Post](https://forum.celo.org/t/proposal-for-funding-stabila-driving-stablecoin-adoption-on-celo)
- [ ] [Github PR]()
```

**Comment by Hawwal** [comment]
Hello @juanjgiraldoc kindly add this to the next governance call. Thanks [Project](https://forum.celo.org/t/draft-blaqk-stereo-consumer-tech-product-dapp-creative-industry-public-good-funding-h1-q2-the-artist-ecosystem/7821?u=hawwal)

**Comment by juanjgiraldoc** [comment]
Hello @Hawwal as said in the Celo Forum _A proposal needs to be up for discussion for at least 7 full days, during which responsiveness from the author is mandatory._ and your proposal was submitted few hours ago. I recomend you to schedule this proposal for next Gov Call.
:bangbang: Agenda now is closed
