### ISSUE TITLE
Celo Governance Call #47 | May 30th, 2024

### ISSUE THREAD

**Issue by work-0xj4an** [celo-org/governance#429]
# Celo Governance Call #47 | May 30th, 2024

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**Before Call Info:**
- When: Thursday, May 30th, 2024, 7:00 PT / 10:00 ET / 14:00 UTC / 16:00 CET 60 minutes max
- Where: [https://lu.ma/CGC-0047](https://lu.ma/CGC-0047)

**After Call Info:**
- Notes: [Here](https://docs.google.com/document/d/1E66-3_J1FHS-x0jHUoawpD8jG_HxJCO_pMke769JyZA)
- Video: [Part 1](https://drive.google.com/file/d/17RvtGxEJluHzwk7a9aJT5HwCvg9MVhai) & [Part 2](https://drive.google.com/file/d/1u_b1kkXpyFwypDmQBC69tJQ8JvrKwUNl)

**Proposals for Discussion**
Crowdsourced on the forum prior to the meeting.
:bangbang: *(Max Proposals per Call: 3 Proposals)*

## Agenda
```[tasklist]
### Topic 1:  Allocate $1M of Mento’s Current Reserve Holdings to Glo Dollar to fund Celo Public Goods at no cost  (12 min Present / 8 Min Q\&A)
- [ ] [Forum Post](https://forum.celo.org/t/draft-allocate-1m-of-mento-s-current-reserve-holdings-to-glo-dollar-to-fund-celo-public-goods-at-no-cost/7927)
- [ ] [Github PR - N.A]()
```

**Comment by juanjgiraldoc** [comment]
## Hello everyone :wave:
No agenda topics have been submitted. We will push this meeting to May 30th, 2024.
