### ISSUE TITLE
Celo Governance Call #48 | Jun 27th, 2024

### ISSUE THREAD

**Issue by work-0xj4an** [celo-org/governance#446]
# Celo Governance Call #48 | Jun 27th, 2024

![Celo Governance Call](https://github.com/celo-org/governance/assets/11728499/8478b28f-8ec3-4945-81f9-d1df8979b758)

**Before Call Info:**
- When: Thursday, Jun 27th, 2024, 7:00 PT / 10:00 ET / 14:00 UTC / 16:00 CET 60 minutes max
- Where: https://lu.ma/9xl443yt 

**After Call Info:**
- Notes: [Here](https://docs.google.com/document/d/1z_xOyi9uPaMw0Fb1RbAlBZoi0FhfnTEn5mdNDin6FsM)
- Video: [N/A]()

**Proposals for Discussion**
Crowdsourced on the forum prior to the meeting.
:bangbang: *(Max Proposals per Call: 3 Proposals)*

## Agenda
```[tasklist]
### Topic 1:  cLabs (20 min Present / 10 Min Q\&A)
- [ ] [Forum Post](https://forum.celo.org/t/clabs-proposes-off-chain-data-availability-layer-powered-by-eigenlayer-and-eigenda/8236)
- [ ] [Github PR](https://github.com/celo-org/governance/pull/452)
```
```[tasklist]
### Topic 2: Mento Airdrop & Governance (10 min Present / 5 Min Q&A)
- [ ] [Forum Post - TBD]()
- [ ] [Github PR - TBD]()
```
```[tasklist]
### Topic 3: CeloPG H2 2024 Budget (10 min Present / 5 Min Q&A)
- [ ] [Forum Post - CeloPG H2 2024 Budget [DRAFT]](https://forum.celo.org/t/celopg-h2-2024-budget-draft)
- [ ] [Github PR - TBD]()
```

**Comment by work-0xj4an** [comment]
Hello everyone :wave: No agenda topics have been submitted. We will push this meeting to Jul 27th, 2024.

**Comment by rcroessmann** [comment]
Hi Juan, I would like to add "Mento Airdrop and Governance" to the agenda for the 27th.

**Comment by work-0xj4an** [comment]
Agenda Closed now.
